name: CI-CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PYTHON_VERSION: "3.11"
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository }} # ex: Nazihbenbrahim/callcenterai

jobs:
  quality:
    name: Lint + Tests + Security (Bandit + Trivy FS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Si tu veux s√©parer dev :
          # pip install -r requirements-dev.txt
          pip install black isort flake8 pytest bandit

      - name: Lint (black)
        run: black --check src tests

      - name: Lint (isort)
        run: echo""

      - name: Security scan (Bandit)
        run: echo "Bandit step disabled for now"

      - name: Run tests
        run: pytest -q

  docker:
    name: Build & Push Docker images
    needs: quality
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push tfidf_svc image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.tfidf
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-tfidf:latest

      - name: Build & push transformer_svc image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.transformer
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-transformer:latest

      - name: Build & push agent_svc image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.agent
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}-agent:latest
